### Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [105]:
 import numpy as np
t=np.arange(1,10+1)
print(t)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
t_zeros=np.zeros((3,3))
print(t_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python

In [14]:
t_evenly=np.linspace(0,5,10)
print(t_evenly)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [16]:
t_ident=np.eye((5))
print(t_ident)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [24]:
a=np.random.seed(0)
a=np.random.rand(4,4)
a

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])


### Exercise 6:
Find the shape of a NumPy array.

In [25]:
a.shape

(4, 4)

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [107]:
b=np.arange(16)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [110]:
b=b.reshape((4,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

In [113]:
b.dtype

dtype('int32')

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [33]:
b=np.arange(2,102,2)
b

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [38]:
b=[x for x in np.arange(100) if x%2==0]
b

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [41]:
t=np.random.randint(10,50,(6,6))
t

array([[41, 11, 11, 49, 45, 48],
       [21, 28, 37, 10, 24, 45],
       [22, 30, 21, 14, 16, 14],
       [13, 22, 46, 24, 25, 30],
       [45, 33, 25, 23, 31, 15],
       [45, 10, 41, 15, 40, 10]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [46]:
t[1:3,:2]

array([[21, 28],
       [22, 30]])

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [49]:
t=np.arange(10)
print(t)
b=sum(t)
print(b)

[0 1 2 3 4 5 6 7 8 9]
45


### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [50]:
m=np.mean(t)
m

4.5

In [52]:
md=np.median(t)
md

4.5

In [53]:
sd=np.std(t)
sd

2.8722813232690143

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [54]:
ma=np.max(t)
ma

9

In [56]:
mi=np.min(t)
mi

0

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [62]:
ar_int=np.random.randint(10,20,size=20)
y=np.argmax(t)
y

9

### Exercise 16:
Create a NumPy array and reverse its elements.

In [63]:
j=np.arange(15)
j

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
np.flip(j)


array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [68]:
t=np.random.randint(1,10,(3,3))
y=np.random.randint(11,20,(3,3))
t*y

array([[ 60,  42,  11],
       [135, 126,  68],
       [171,  33, 171]])

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [72]:
g=np.arange(12)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
np.diag(g)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11]])

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [76]:
m1=np.random.randint(1,5,(2,2))
print(m1,"\t")
m2=np.random.randint(6,10,(2,2))
print(m2,"\t")
p=m1.dot(m2)
print(p)


[[4 2]
 [3 2]] 	
[[9 7]
 [9 6]] 	
[[54 40]
 [45 33]]


In [78]:
b=np.multiply(m1,m2)
b

array([[36, 14],
       [27, 12]])

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [81]:
h=np.arange(12)
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
b.flatten()

array([36, 14, 27, 12])

### Exercise 21:
Stack two NumPy arrays vertically

In [94]:
a1=np.arange(2,12)
q2=np.arange(22,32)
print(np.vstack((a1,q2)))

[[ 2  3  4  5  6  7  8  9 10 11]
 [22 23 24 25 26 27 28 29 30 31]]


### Exercise 22:
Stack two NumPy arrays horizontally.

In [98]:
print(np.hstack((a1,q2)))

[ 2  3  4  5  6  7  8  9 10 11 22 23 24 25 26 27 28 29 30 31]


### Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [104]:
#x=np.arange(1,12)
x1=np.random.randint(1,10,size=10)
np.split(x1,2)

[array([6, 9, 3, 4, 8]), array([6, 4, 5, 6, 4])]

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [115]:
print(np.round(np.random.rand(1,10,),2))

[[0.41 0.07 0.7  0.45 0.72 0.87 0.98 0.86 0.01 0.36]]


### Exercise 25:
Find the unique elements of a NumPy array.

In [116]:
t= np.array([1, 0, 0, 5, 56,7, 1, 0, 0, 5, 56,7, 23, 2, 3, 4, 40,40])
np.unique(t)

array([ 0,  1,  2,  3,  4,  5,  7, 23, 40, 56])

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [117]:
g=np.random.randint(1,9,size=5)
g

array([6, 2, 5, 3, 3])

In [118]:
u= np.array([[1, 0, 0, 5, 56,7], [1, 0, 0, 5, 56,7], [23, 2, 3, 4, 40,40]])
u[u<=0]=200
u

array([[  1, 200, 200,   5,  56,   7],
       [  1, 200, 200,   5,  56,   7],
       [ 23,   2,   3,   4,  40,  40]])